name: main

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Read version from csproj
        run: |
          $selectResult = Select-String -Path ".\src\Serilog.Sinks.MSSqlServer\Serilog.Sinks.MSSqlServer.csproj" -Pattern '<VersionPrefix>(.+)</VersionPrefix>'
          $versionMatch = $selectResult.Matches[0].Groups[1].Value
          echo ("VERSION=" + $versionMatch) >> $env:GITHUB_ENV
          echo "Found version $versionMatch"

      - name: Print GitHub event
        run: |
          echo "GitHub event is ${{ github.event }}"

      - name: Run build
        if: ${{ github.event != "PullRequestEvent" }}
        run: ./Build.ps1

      - name: Run build and tests
        if: ${{ github.event == "PullRequestEvent" }}
        run: ./Build.ps1 -RunTests $true

      - name: Create releease
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ env.VERSION }}-test"
          draft: true
          title: "v${{ env.VERSION }}-test"
          files: |
            artifacts/*.nupkg
            artifacts/*.snupkg
