name: main

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Read version from csproj
        run: |
          $selectResult = Select-String -Path ".\src\Serilog.Sinks.MSSqlServer\Serilog.Sinks.MSSqlServer.csproj" -Pattern '<VersionPrefix>(.+)</VersionPrefix>'
          $versionMatch = $selectResult.Matches[0].Groups[1].Value
          echo ("VERSION=" + $versionMatch) >> $env:GITHUB_ENV
          echo "Found version $versionMatch"

      - name: Run build script
        run: ./Build.ps1
          
      - name: Create releease
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ env.VERSION }}-test"
          draft: true
          title: "v${{ env.VERSION }}-test"
          files: |
            README.md
            D:\a\serilog-sinks-mssqlserver\serilog-sinks-mssqlserver\artifacts\Serilog.Sinks.MSSqlServer.5.7.0.nupkg
            artifacts\Serilog.Sinks.MSSqlServer.${{ env.VERSION }}.snupkg
            **/*.snupkg
