name: Performance Tests

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-perftest:
    runs-on: windows-latest # Build on Windows to ensure .NET Framework targets
    steps:
      - uses: actions/checkout@v4

      - name: Run build
        run: ./Build.ps1 -SkipTests
        shell: pwsh

      - name: Run performance tests
        run: ./RunPerfTests.ps1 -Filter ${{ secrets.PERF_TESTS_FILTER }}
        shell: pwsh

      - name: Upload perf test results artifact
        uses: actions/upload-artifact@v4
        with:
          name: perftestresults
          path: artifacts\perftests
