name: PR Validation

on:
  pull_request:
    branches: [ dev, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run build and tests
        run: ./Build.ps1
