name: PR Validation

on:
  pull_request:
    branches: [ dev, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run build and tests
        run: ./Build.ps1

      - name: Upload binaries artifact for InferSharp workflow
        uses: actions/upload-artifact@v3
        with:
          name: bin-net6
          path: src\Serilog.Sinks.MSSqlServer\bin\Release\net6.0
